---
title: "notes"
output: html_document
---

# Segment 1
- weekenends are downs, except if weekend is a month end
- month end peaks have come down in since Apr 2018
- peaks on mondays
- 2019 - peaks on monday, down till wednesday, up till friday
- Formula: mean + week_of_month  - is_weekend +/- weekday + end_of_month_date

# Segment 2
- weekends are downs (that too Sundays), exception: aug weekend 2
- ups are in week 2 and 3 of the month
- 3 peaks since July 2018, 3rd peak is mostly lower than first two peaks
- trending up, but 2019 is lower than 2018, so not a linear trend
- recency has more weight in terms of years
- Formula: too tired!

# Decomposition ToDo
- make series continuous
- define frequency
- see how default outcome of stl decomposition looks like - use mstl()
- define trend and seasonal hyperparameters for stl decomposition
- model seasonally adjusted time series using different models
    - use methods in stlf()

# immediate next steps
- Try by decomposing for each year separately and then creating features separately too
- add holidays in s1
- add rolling features
- add tbats prediction as feature
- make negatives zero

# toDo next models
- add 
- dynamic models
- hierarchical
- prophet

Things to note
- just 5 submissions
- don't overfit
- train on train + validation



test - segment 1 - July 6 to Sept 30
test - segment - July 24 to Oct 24

-09-30

- diwali pe badhti hai
- oct 2 ko zero hai
- low on labr day
