# ToDo
- Base models without filling in for missing dates
- SARIMA, ETS
- include holidays
- LSTM


```{r}
temp_data <- train_preped %>%
  dplyr::filter(segment == "s_1", zone == "NORTH", state == "PUNJAB", branch_id == "b_15")

start_date <- min(temp_data$application_date)
end_date <- max(temp_data$application_date)
date_seq <- seq(start_date, end_date, by = "day")

temp_data_continuous <- data.frame(application_date = date_seq) %>% 
  left_join(dplyr::select(temp_data, application_date, case_count)) %>% 
  mutate(case_count = ifelse(is.na(case_count), 0, case_count))

application_count_ts <- ts(temp_data_continuous$case_count, start = c(year(start_date), yday(start_date)), end = c(year(end_date), yday(end_date)), frequency = 365)
```

```{r}
# application_count_ts %>% 
#   cpt.meanvar() %>% 
#   plot()
```

```{r}
temp = data.frame(a=c('a','a','b'), b=c('a1','a2','b'), c=1:3)

temp %>% 
  group_by(a) %>% 
  summarise_all(lst(~if(is.numeric(.)) mean(.) else first(.)))

temp %>% 
  group_by(a) %>% 
  summarise_all(~first(.))
```

```{r}
temp = data.frame(a = ymd(c("2019-01-01", "2019-01-01", "2019-01-02", "2019-01-04")), b = c("a", "b", "c", "a"), count = 1:4)
temp
temp %>% 
  complete(a = seq(ymd("2019-01-01"), ymd("2019-01-04"), by="days"), nesting(b)) %>% 
  arrange(b)
temp %>% 
  complete(a = seq(ymd("2019-01-01"), ymd("2019-01-04"), by="days"), nesting(b)) %>% 
  group_by(b) %>%
  fill(`count`) %>% 
  arrange(b)
```

